name: .NET Build & Test

on:
  workflow_call:
    inputs:
      dotnet_version:
        required: true
        type: string
      publish_project:
        default: '.'
        required: false
        type: string
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish -c release -o publish --no-restore ${{ inputs.publish_project }}
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: publish
        path: publish
